### ISSUE TITLE
issue with libjack and pipewire-libjack ?

### ISSUE THREAD

**Issue by ahjolinna** [mpc-qt/mpc-qt#101]
it seems I can't run latest version 23.12  (rpm & AppImage) as it complains about libjack.so.0 missing.

I notice that I have pipewire-libjack-0_3 installed which does provide libjack.so.0, but for some reason it requires the libjack0 pkgs (and its in conflict with pipewire pkgs)

pipewire file location is at /usr/lib64/pipewire-0.3/jack/libjack.so.0 which is different from libjack0 which why it wont find it

**Comment by cmdrkotori** [comment]
What distro?

**Comment by ahjolinna** [comment]
openSUSE (microOS/Kalpa)

**Comment by ahjolinna** [comment]
notice that digikam had this same issue https://forums.opensuse.org/t/digikam-fails-to-start-with-error-while-loading-shared-libraries-libjack-so-0/166682/8

**Comment by cmdrkotori** [comment]
That's OpenSUSE's own fault.  https://bugzilla.opensuse.org/show_bug.cgi?id=1211926

OpenSUSE needs to make pipewire-jack hard conflict with regular jack like other distros do, so that pipewire-jack can be installed in its standard location.

In the meantime add a libjack.so.0 symlink in /usr/lib64 to /usr/lib64/pipewire-0.3/jack/libjack.so.0.

**Comment by cmdrkotori** [comment]
Anyway, I hope this fixes the issue.  There were some other possible fixes in that bug report, (such as running zypper in pipewire-jack,) but lacking a real opensuse system (I haven't personally used it in 15 years tbh) I can't recommend anything one way or the other.

**Comment by ahjolinna** [comment]
yeah, it seems you have to install pipewire-jack for it to work ...sigh
