### ISSUE TITLE
volume control behavior like MPC-HC/MPC-BE

### ISSUE THREAD

**Issue by amayra** [mpc-qt/mpc-qt#12]
1- would please make volume control with mouse wheel like mpc-like media player when i can control the volume with mouse wheel in any place in app not only black space  

2- can i make mpc-qt go in music player mode without cover art or black place where video is supposed to be played and keep the ability to control the volume with mouse wheel

music player mode like this : [https://en.wikipedia.org/wiki/Media_Player_Classic#/media/File:Media_Player_Classic-6.4.8.3_on_Wine.png](https://en.wikipedia.org/wiki/Media_Player_Classic#/media/File:Media_Player_Classic-6.4.8.3_on_Wine.png)

**Comment by cmdrkotori** [comment]
1. It is theoretically possible for us to do that, yes.
2. You can make mpc-qt go into "music player mode" by turning off video size snapping (Alt+0), dragging the playlist window to the anchor to the bottom edge, and then resizing the window so that the video area disappears. Like this:
![Screenshot_20211101_115808](https://user-images.githubusercontent.com/65291121/139611356-0160d7a1-3ca3-45dc-a597-7c66a75086f2.png)

**Comment by amayra** [comment]
when I do that I can't control the volume with the mouse wheel anymore 
I hope you fix it soon if not too much work for you 
and thank you for this amazing media player for people who move to Linux and still don't get how thing work yet like me
