### ISSUE TITLE
Left click not working

### ISSUE THREAD

**Issue by Macaquinyo** [mpc-qt/mpc-qt#124]
I recently updated from an old version, and (double) left click does no longer do what it's assigned to do. The only thing I can do with a left click is activating that drag the window mode.
I also tried to bind something to key+left click. Doesn't work either.

Tried launching with --no-config and --no-files. Same symptoms.

**Comment by cmdrkotori** [comment]
By default the only thing a right-click will bring up is the context menu.  Also the code never explicitly checks the right mouse button for anything.  Do you perhaps have left handed mouse on?

This seems odd. What's your OS? Window manager?

**Comment by Macaquinyo** [comment]
Well, this is embarrassing... I meant the left click. Ups.

**Comment by cmdrkotori** [comment]
As far as keys/shortcuts go, the recent change with the default keys is that Left-Click-Release is now bound to pause, rather than Left-Click-Press.  This change was to facilitate click dragging from the video area.  Dragging happens only when the mouse has moved after the left mouse button is held down.  Running with `--no-config` should have picked up this change.`

In any case, I'll see if I can reproduce this in a VM.

**Comment by cmdrkotori** [comment]
Reproduced.  By default git master is still set to Click-Down, not Click-Release.

**Comment by cmdrkotori** [comment]
Git pull + recompile and it should pick up the new default.

**Comment by cmdrkotori** [comment]
Double click detection still isn't working.

Why?  Because we tell the toolkit to not process the click to stop a window-dragging bug.  This is probably also stopping my left-click-press detection code from working because it's not getting passed up the chain.  Blame #28 for this mess.

I may have to do some wheel reinventing to get double click working again if we want to keep window dragging.

**Comment by Macaquinyo** [comment]
Left down also does not work for any action... I think. What are "left up" and "left down" even supposed to mean? Pressing and releasing? Clicking on the top and the bottom of the window? I cannot make any sense of it, at least with the Spanish translation...

Also, if you assign full-screen to left up, and drag the window, when you release the click the window goes full screen in the incorrect position and you are still dragging it... So it is broken. I guess no one would assign full-screen to left click, though.

 I suggest making it so that you have to click & hold for some time (200ms?) before it enters dragging mode. Though I don't know the codebase, that may not be possible.

**Comment by cmdrkotori** [comment]
Left Up and Left Down are indeed Left Press and Left Release.

**Comment by cmdrkotori** [comment]
Funcitionality restored.  You should be able to assign things to left-press again.

>What are "left up" and "left down" even supposed to mean? Pressing and releasing? Clicking on the top and the bottom of the window? I cannot make any sense of it, at least with the Spanish translation...

Left Up and Left Down are indeed Left Press and Left Release.  Perhaps it's the English that's ambiguous.

**Comment by Macaquinyo** [comment]
Everything confirmed working. Thank you!

And many thanks for developing mpc-qt!
