### ISSUE TITLE
[Feature request]: Like bomi Subtitle viewer, Potplayer Subtitle Browser

### ISSUE THREAD

**Issue by gitut2007** [mpc-qt/mpc-qt#13]
Hi. For this very cool feature found in bomi : 'Subtitle viewer' [ "Subtitle Browser" in Potplayer].
-You can at any moment read what just passed [sometimes the film goes too fast, or one wasn't paying attention]
-You can doble-click any line and the movie goes to that time
-You can compare subs to choose the best, or to compare dif languages... in the pics:
 https://1fichier.com/?m3qnlbm75yew9hjzsh9s 
-bomi can show 2, 3 [or more!] subs at the same time. Since bomi is also based in mpv, maybe you could look at its code... https://github.com/xylosper/bomi/ ; 
https://1fichier.com/?zftg86prenqixyy2w9i6 
-Potplayer [on the video it can display 2 srt files, but on the Subtitle Browser only 1]. If the subs are coloured [srt here] it shows the colors. [also there are edit and sync functions there]
Thx

**Comment by cmdrkotori** [comment]
I think subtitle browsing is a great feature that is out of scope for this project. We aim to be a straightforward libmpv wrapper with an interface matching mpc-hc. libmpv last time I checked did not expose decoded subtitles in a meaningful way that would allow us to writer a browser, so that's a this feature is simply not possible on my end.
Bomi on the other hand has features like this that need much original code. I did look at its subtitle parser. I'm not prepared to take on such an undertaking for this simple project.
