### ISSUE TITLE
mpc-qt locks file folder after start

### ISSUE THREAD

**Issue by asianmusicguy** [mpc-qt/mpc-qt#26]
so i have 2 things about this program that scare me @cmdrkotori 
1. file folder locks after launch so folder is undeletable  despite closing the program  if i want to remove the folder 
. system claims i need permission  despite being admin what might be causing this?
2. Emsisoft  antimalware also claims the .exe for mpc qt as a cryptomalware

**Comment by cmdrkotori** [comment]
1. I have no idea why the folder would be locked after the program is closed. Perhaps something else is using the folder? We don't do any file locking here other than what windows does by itself.
2. False positive and I'm not surprised. The host part of a handy tool I use called [looking-glass](https://looking-glass.io/) also gets flagged and deleted on my system. You are welcome to compile mpc-qt yourself; because it was compiled only recently, you will likely end up with the same executable. Alternatively, your system may be compromised.

**Comment by asianmusicguy** [comment]
Thanks I don't think it has anything to do with my system being compromised ill go with the false positive assumption  
The folder being locked though only occurs after i launch the  program and exit do if we can figure that out or you could test a little that be great

otherwise ill submit the false positive to emsisoft

**Comment by cmdrkotori** [comment]
Thanks mate, that would be great. Cheers.

**Comment by asianmusicguy** [comment]
@cmdrkotori Thought you might wanna know your program is  white listed atlest via emsisoft
