### ISSUE TITLE
Feature request: Drag viewport to move window (Xorg)

### ISSUE THREAD

**Issue by AlexFolland** [mpc-qt/mpc-qt#28]
I am using Manjaro unstable with the latest XFWM4 and xorg-server as of this request.

In my desktop environment, video players MPV, SMPlayer, and VLC can all move the window by starting a click and drag on the video viewport, even while the left mouse button is also bound to the play/pause action.  This is especially useful when all GUI elements are hidden except the viewport.

This ticket is to request the addition of this feature in mpc-qt.  It would improve my personal enjoyment of the software.

A good reference for how well this works even while the left mouse button is also bound to the play/pause action is SMPlayer.  In SMPlayer, the play/pause action (or any other action bound to the left mouse button) is only triggered if the cursor did not move between mousedown and mouseup, and otherwise the window is dragged.

I am not implying this is possible or easy, nor am I demanding the feature.  I am only gently requesting it.  Thank you for your work on this software.  It is excellent.

I also have no idea whether this is possible with Wayland.  I don't use Wayland because I've heard it has limitations with software which positions and sizes its own windows, and has no user-facing advantages if your desktop already renders without frame drops and tearing under Xorg, which mine does.

**Comment by cmdrkotori** [comment]
>In my desktop environment, video players MPV, SMPlayer, and VLC can all move the window by starting a click and drag on the video viewport, even while the left mouse button is also bound to the play/pause action. This is especially useful when all GUI elements are hidden except the viewport.

Sure.

>I also have no idea whether this is possible with Wayland. I don't use Wayland because I've heard it has limitations with software which positions and sizes its own windows, and has no user-facing advantages if your desktop already renders without frame drops and tearing under Xorg, which mine does.

We explicitly force XCB instead of wayland because wayland's window management is broken by design, and sane window management is more important for me than any """"benefit"""" that wayland brings. I believe you can blame some of the sway devs for this situation. Wayland breaks these three settings:
![Screenshot_20220222_082238](https://user-images.githubusercontent.com/65291121/155033055-6f8ea183-39a5-48f6-a42c-3916b612d73f.png)
![Screenshot_20220222_082321](https://user-images.githubusercontent.com/65291121/155033083-c7da743c-1b69-4185-9731-40ca1993d954.png)
![Screenshot_20220222_082352](https://user-images.githubusercontent.com/65291121/155033092-44ddf6f2-165f-46e4-a63d-e17767d6d530.png)
Until that is fixed, I couldn't care less about wayland.

**Comment by AlexFolland** [comment]
Just to clarify here, I also don't use Wayland and this feature request is not requesting implementation with or in Wayland.  I agree with you.

**Comment by he3als** [comment]
If implemented, I presume this would also work on Windows?

**Comment by AlexFolland** [comment]
The title specifies "Xorg", so if the feature request was fulfilled as written, it would not.

**Comment by he3als** [comment]
Click to drag is also available on the Windows versions of the players that you mentioned, as a note

**Comment by AlexFolland** [comment]
Yes, of course it would be a benefit for Windows users for a Windows-specific implementation of this feature to also be implemented for Windows, but that's not part of this particular feature request.

**Comment by cmdrkotori** [comment]
I think this is possible, although I don't think Qt has an API for voluntarily entering a window drag on wayland.  Or any platform for that matter.  For Wayland, I'd need to access the underlying platform and do it raw, which isn't what one would call good code.  For other platforms it can be done à la wheel-reinventing with cursor tracking + window move events, the usual way.  I could simply not do this on wayland.

Re: the other apps you mentioned.

Smplayer forces use of xcb and will fail to run if DISPLAY is not set.  So it can always fake a window move whenever it wants.

As for vlc, unsetting DISPLAY and forcing the fusion style with QT_STYLE_OVERRIDE=fusion does not allow the window to be dragged by the viewport.  On Linux, it's a feature of the Breeze theme to enter window drag from window areas, not vlc.  I haven't tested vlc on Windows to see if it does that there too.

mpv talks wayland natively and can enter a window drag from the viewport.

So that's the state of this.  A platform-specific code path is needed for wayland, and faking a window move for everyone else.

**Comment by cmdrkotori** [comment]
Ok, so there's a new api for entering a window move in Qt 6.  [QWindow::startSystemMove](https://doc.qt.io/qt-6/qwindow.html#startSystemMove)

ETA for when I can write this: after I work on the thumbnail code

**Comment by AlexFolland** [comment]
I've tried this implementation now, and it's almost right, but it's sticky.  The window sticks to my cursor after I release the mouse button.  I have to give it a full click again to get it unstuck.

**Comment by AlexFolland** [comment]
I don't have a button to reopen the feature request.  Should it be reopened, or should I make a new related ticket?

**Comment by cmdrkotori** [comment]
> The window sticks to my cursor after I release the mouse button. I have to give it a full click again to get it unstuck.

I can't fix that.

>Also, it performs a pause/play action at the same time as the drag start, even though the cursor did move between the button-down and button-up events.

It's working as configured.  I can rebind the default play/pause to the mouse up action, but that will merely change when the play/pause happens (at the end or middle of the drag when the mouse button goes up).  Pausing the video when you make a time-intensive drag operation would seem to be the better of the two options.

**Comment by AlexFolland** [comment]
What makes fixing these impossible?  SMPlayer can be dragged from its viewport without play/pausing and still play/pause when clicking when the cursor didn't move between the mouse-down and mouse-up events.  It also doesn't get stuck.  These behaviors are both on the same desktop as I am testing `mpc-qt-git`.

**Comment by cmdrkotori** [comment]
SMPlayer is forcing use of xcb (X11/Xorg) and faking it by spamming the toolkit with move requests and global mouse tracking.  I'm doing it the proper way that works on both wayland and xcb, by calling a system function that does it for me.  I'm not going to force xcb for everyone again just for this.  And it's impossible for me to fix because I'm not in charge of the nuances of what system code is or does, sorry.

If you don't like it so much, unbind play/pause from the mouse.  I'm leaving it this way.

**Comment by cmdrkotori** [comment]
> What makes fixing these impossible? SMPlayer can be dragged from its viewport without play/pausing and still play/pause when clicking when the cursor didn't move between the mouse-down and mouse-up events. It also doesn't get stuck to the cursor and require another click. These behaviors are both on the same desktop as I am testing `mpc-qt-git`.

After some digging, the issue above has been fixed in 8b2651d2b9d721560d9eca3d877a9022c6a34010.

**Comment by AlexFolland** [comment]
Thank you!  I'm away from my usual computer in another country right now, but I'm commenting to let you know I appreciate your effort!

I was also working on this problem in the MPC-QT code myself a while back, shortly after you commented, and I managed to fix one of the 2 issues, but not the other, so I wasn't satisfied enough to open a pull request.  I'll test your fix shortly after I arrive in my home country.

**Comment by cmdrkotori** [comment]
I should add this it works perfectly in wayland, but not X11 which still has the click bug.

Ironic, because manipulating the playlist window while its floating is broken on wayland, but not X11.

**Comment by AlexFolland** [comment]
I may have the solution for the click bug in X11 then, if I still have my local changes on my home PC.  I'll let you know if I do.

**Comment by cmdrkotori** [comment]
No need, fixed in master.

**Comment by AlexFolland** [comment]
Thanks!  I just got home yesterday and hadn't had time to revisit my potential fixes and pull request yet.  Instead, I've seen your update, and I've just now fresh-built AUR package `mpc-qt-git` to test this and confirmed that all the issues I had previously reported with the implementation were resolved on my system!  Thank you very much for this.
