### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by cmdrkotori** [mpc-qt/mpc-qt#32]
This issue for tracking the development of a future website.

I have this mock-up at the moment, though it is nothing to look at.

![Screen Shot 2022-03-02 at 14 16 01](https://user-images.githubusercontent.com/65291121/156294398-f21d7ba2-d238-43a7-8eff-32fac0033279.png)

Any suggestions are welcome.

**Comment by ahjolinna** [comment]
reminds me of [bomi-players site](https://bomi-player.github.io/) ....and that's fine is should be something simple (less is more), anyway I would take some references ideas from bomi (for example the text on what/how to emphasise stuff).

some few good screenshots are important (bomi and others usually fail on this), the one you have currently, is okay
(maybe some small gif's ...instead of video clips)

**Comment by cmdrkotori** [comment]
Website published at https://mpc-qt.github.io/
