### ISSUE TITLE
Discussion about "Possible upcoming features"

### ISSUE THREAD

**Issue by goyalyashpal** [mpc-qt/mpc-qt#67]
_This_ may _sound like rant, but I am not ranting. I am writing this with aim to just get my point across from various different angle of views._

-----

> **Native filter-chain support:**
> Comprehensive integration of mpv/ffmpeg's filter interface/library, right inside your media player.
>
>  **Encoding support like VirtualDub:**
> No need to open a video editor when your media player can do your job for you.

- These features are video-editing oriented.
... which most people don't use when using a video-_player_.

- These features are wayyy too expensive all around - high performance cost, 
super demanding UX design, high development-&-maintenance requirement.

- And ofcourse these steal time from the devt of the main video player,
... only to eventually get whole project abandoned by the authors due to that.

- What you get in the end is bloated piece which _neither stays a good video player_; 
and was _never a solid video editor_ in the first place;

- VLC is a good example of this semi-video-editing bloat, and is now forever stuck in past.

The readme itself says:
> This feature may entail a lot of code. 
> Requires writing an encoder-orientated backend. 

These features if wanted:
- should be kept modular & plug-n-play with little impact on the main player. 
- That is, implement as separate plugins or additonal installable modules. 

The UNIX philosophy, & MS VS Code can be look as an example: "Doing
one thing, & doing it better". Convoluting does NOT help.

People want a _player_ that works, and works well and stays relevent with time.
Today, no alternates exist for VLC which are FOSS, frontended, maintained, 
& cross platform - only [SMPlayer] frontend to MPV. 

I don't want to see _yet another_ option die.

[SMPlayer]: https://github.com/smplayer-dev/smplayer/

Yeah, if this is only intended as a personal enjoyment project, then sure, go ahead.
But if intended as even a remote means to rectify the situation with players, then 
I'd say please rethink for these fantasy-tical ideas.

----
Citations:

> Other things such as ricing or the encoding support like virtualdub or webm-for-gits when I get to it are a novel addition
> \- @ cmdrkotori at https://github.com/mpc-qt/mpc-qt/issues/21#issuecomment-1045667154

https://github.com/mpc-qt/mpc-qt/blob/fd5ff27dd9efe84f34611609c42dabe0c47e3b4f/README.md#L60-L70

**Comment by cmdrkotori** [comment]
>Yeah, if this is only intended as a personal enjoyment project, then sure, go ahead.

It started out as a personal project. In fact all the features implemented thus far are what I used in mpc-hc day to day, with a few exceptions such as the web server. The remaining stuff in mpc-hc that are yet to be copied are stuff I don't use.

>But if intended as even a remote means to rectify the situation with players, then
I'd say please rethink for these fantasy-tical ideas.

If it helps you, you should know that native filter-chain support is on the chopping block because when I looked into filters a a few months ago, it became apparent that ffmpeg devs have not provided a run-time method of scraping available filters and their parameters. Every sort of filter has to be hard-coded. So not only does supporting 300 filters require a lot of code, it is impractical as it stands. Especially for a single developer. So I think what we're going to do is support only a handful of filters like bomi did and leave it at that; if nothing changes filter-chains are going to be dropped.

On the other hand, encoding support is pretty easy I'd say. (600 lines of code maybe?)

I hope that puts your mind at ease. If you have any more concerns, don't hesitate to ask.
