### ISSUE TITLE
Editing mpv config

### ISSUE THREAD

**Issue by 12345678902wsx** [mpc-qt/mpc-qt#7]
I'd like to change the config of mpv, but I can't seem to find the config file.
Is it possible to change the config? If so, where should it be located.

**Comment by cmdrkotori** [comment]
You should ask the mpv devs.

**Comment by casta** [comment]
Hi,

I’m not sure it’s necessarily an MPV issue.
I think that the requested feature is to be able to pass custom parameters to libmpv, since it’s not possible to add a parameter in the configuration panel for every single mpv option.

The simple way I see would be to allow to set a custom list of parameters (free text). And this can be done on mpc-qt side.
An other way would be to be able to read .mpv/config (or something else) to inject the configuration in libmpv. I suppose that this is what should be asked to mpv devs?

For example, on my side, I would like this feature to add this: `af=lavfi=[acompressor=ratio=4,loudnorm]` (currently I solved it by patching mpvwidget.cpp, but it’s ugly, and I have not the C++ knowledge to make a merge request…)

Regards

**Comment by cmdrkotori** [comment]
Adding lavfi filters to mpc-qt is a planned moonshot feature that'll be started on as soon as the settings window is finished. Which has been ongoing for five years now. (the program was 'complete' before we added it.) The lavfi patchbay will be a rip off the systray patchbay available if you install [ffdshow-tryouts](http://ffdshow-tryout.sourceforge.net/).

If someone wants lavfi filters sooner, they can help patch out the missing functionality needed to make the greyed-out settings work. Or wait patiently for me to get to it.

**Comment by cmdrkotori** [comment]
@casta I've put together a mockup of some lavfi C++ code in #19
