### ISSUE TITLE
Option to use Wayland

### ISSUE THREAD

**Issue by lgdsgd2000** [mpc-qt/mpc-qt#72]
I see https://github.com/mpc-qt/mpc-qt/issues/54 and would like to ask if it is possible to support wayland in the future.I love this player,just an expectation.

**Comment by cmdrkotori** [comment]
The program already works under wayland.

**Comment by cmdrkotori** [comment]
We disable the wayland platform and use xwayland because of wayland's lack of modern window management code. It breaks all the code in `platform/windowmanagement.cpp`.  This can be easily seen by placing the window in the bottom right corner and playing a video that takes most of the screen. On xwayland I can prevent it going completely off screen as one would expect, but I can't on wayland. Simple as. This isn't changing until particular wayland developers in charge of the spec stop screwing it up for everyone who needs window code that works.

**Comment by cmdrkotori** [comment]
>I don't get why it is hardcoded and not implemented e.g. as a toggle in the settings.

Well I guess we can do that. It's a bit of a pain to write so much windowing code and wayland not supporting it.

**Comment by cmdrkotori** [comment]
>generally hate when windows are trying to control their geometry.

You are welcome to feel that way as a user of a tiling window manager. However the experience is horribly broken without management of our own geometry on a stacking window manager.

>disabling "Remember last window geometry" option causes the playlist tab to reopen on every launch.

Of course? The location of the playlist tab is part of its window geometry.

**Comment by cmdrkotori** [comment]
>Why in the world someone will want to watch a video e.g. in 2/3 of the screen, what's the point?

That would be people like me, who's field of view (eyesight) is not that great.

**Comment by cmdrkotori** [comment]
>Either way actual video resolution does not matter and autosizing is seemingly pointless. Why in the world someone will want to watch a video e.g. in 2/3 of the screen, what's the point?

Getting back to your point, this is for the simple reason that mpc-hc supports zoom-factors et al and mpc-qt has to support them too.

Anyway, I use the auto-zooming functions of mpc-qt to handle resizing for me so I can take note of everything happening in the video frame, every single time. So I don't have to think all that much about it. If I didn't miss this feature, I'd still be using mpv and this program would not exist.

Thanks for understanding.
